
from logging import exception


class tweetcont:
    def __init__(self, orginaltweet):
        self.originaltweet = originaltweet
        

    def processtweet(self):
        return self

def main():
    test = tweetcont('/Users/matt/Desktop/VCTrendy/list.txt')
    print("Completed!")

if __name__== "__main__":
    main()
    
